name: "Deploy victor app"

on:
 push:
  tags:
    - "victor-app/TP3-V*"

env:
  PROJECT_PATH: TP214E/TP214E.csproj

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - run: dotnet restore ${{ env.PROJECT_PATH }}

      - run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - run: dotnet build ${{ env.PROJECT_PATH }} -c Release self-contained -r win-x64 -p:PublishSingleFile=true